id: ingest-api-to-csv
namespace: examples.api

tasks:
  - id: fetch-api
    type: io.kestra.plugin.core.http.Request
    method: GET
    retry:
      type: constant
      interval: PT10S
    uri: https://jsonplaceholder.typicode.com/users2

  - id: convert-to-csv
    type: io.kestra.plugin.scripts.python.Script
    outputFiles:
      - output.csv
    script: |+
      import json
      import csv

      data = """{{ outputs["fetch-api"]["body"] }}"""
      users = json.loads(data)

      with open("output.csv", "w", newline="") as csv_file:
          writer = csv.DictWriter(csv_file, fieldnames=users[0].keys())
          writer.writeheader()
          writer.writerows(users)